"""Make a C header file from an HTML file for use with ESP8266/ESP32 Arduino projects."""

from datetime import datetime

INPUTFILE = "index-min.html"
OUTPUTFILE = "../index-min.h"

HEADER_INFO_PREFIX = '''// This file is generated by headerfy.py at ''' + datetime.now().strftime("%Y-%m-%d %H:%M:%S") + '''\n'''

HEADER_PREFIX = '''const char index_html[] PROGMEM = R"=====(\n'''
HEADER_SUFFIX='''\n)=====";'''

with open(INPUTFILE, 'r', encoding='utf-8') as f:
    html = f.read()

with open(OUTPUTFILE, 'w', encoding='utf-8') as f:
    f.write(HEADER_INFO_PREFIX)
    f.write(HEADER_PREFIX)
    f.write(html.replace('"', '\\"').replace('\n', '\\n'))
    f.write(HEADER_SUFFIX)
    f.write('\n// Bytes: ' + str(len(html)) + '\n')
